<?php
/**
 * App Release Auto-Publisher (Automation of the manual "publish new app version" step)
 *
 * Every panel instance (main or any reseller white-label instance) runs this from cron.
 * It fetches the `app_release.json` manifest published by the CI pipeline as a GitHub
 * Release asset and, when a strictly newer app build exists, publishes it into the
 * panel settings automatically:
 *
 *   app_latest_version / app_update_changelog / app_update_title / app_update_source
 *
 * Precedence rules (so the admin always stays in control):
 *   - `app_update_source = 'admin'`  -> manual publish; auto-publisher NEVER overwrites
 *   - `app_update_enabled  = '0'`    -> updates intentionally disabled; nothing published
 *   - otherwise (source 'auto' / empty) -> auto-publisher keeps apps up to date
 */
require_once __DIR__ . '/Database.php';
require_once __DIR__ . '/Setting.php';
require_once __DIR__ . '/Updater.php';

class AppReleasePublisher
{
    /** Release tag that the CI pipeline publishes APK assets to */
    public const RELEASE_TAG = 'v3.0.0';
    /** Manifest asset name generated by the CI pipeline */
    public const MANIFEST_ASSET = 'app_release.json';
    /** Minimum seconds between two GitHub checks (called from cron every ~3 min) */
    public const CHECK_INTERVAL = 300;

    /**
     * Run one auto-publish cycle. Safe to call any time; throttled internally.
     * Returns a status array (also cached for UI display).
     */
    public static function sync(): array
    {
        $lastCheck = (int)Setting::get('app_release_last_check', '0');
        $status = json_decode(Setting::get('app_release_status_cache', '{}'), true) ?: [];

        if (time() - $lastCheck < self::CHECK_INTERVAL) {
            $status['skipped'] = 'throttled';
            return $status;
        }
        Setting::set('app_release_last_check', (string)time());

        $repo = Updater::getRepo();
        $token = Updater::getToken();

        // 1. Locate the manifest asset in the pinned release
        $release = Updater::githubRequest(
            "https://api.github.com/repos/{$repo}/releases/tags/" . self::RELEASE_TAG,
            $token
        );
        $asset = null;
        if (is_array($release) && isset($release['assets'])) {
            foreach ($release['assets'] as $a) {
                if (($a['name'] ?? '') === self::MANIFEST_ASSET) {
                    $asset = $a;
                    break;
                }
            }
        }

        $status['checked_at'] = date('Y-m-d H:i:s');
        $status['repo'] = $repo;

        if (!$asset || empty($asset['browser_download_url'])) {
            $status['ok'] = false;
            $status['error'] = 'manifest_not_found';
            Setting::set('app_release_status_cache', json_encode($status));
            return $status;
        }

        // 2. Download + parse the manifest
        $manifest = self::fetchJson($asset['browser_download_url']);
        if (!$manifest || empty($manifest['version'])) {
            $status['ok'] = false;
            $status['error'] = 'manifest_invalid';
            Setting::set('app_release_status_cache', json_encode($status));
            return $status;
        }

        $remoteVer  = trim((string)$manifest['version']);
        $changelog  = trim((string)($manifest['changelog'] ?? ''));
        $currentVer = trim((string)Setting::get('app_latest_version', ''));
        $source     = (string)Setting::get('app_update_source', 'auto');
        $enabled    = Setting::get('app_update_enabled', '1') !== '0';

        $status['ok'] = true;
        $status['remote_version'] = $remoteVer;
        $status['published_version'] = $currentVer;
        $status['published_at'] = (string)Setting::get('app_update_published_at', '');

        $isNewer = !empty($currentVer)
            ? version_compare($remoteVer, $currentVer, '>')
            : (version_compare($remoteVer, '0.0.0', '>'));

        if ($isNewer && $enabled && $source !== 'admin') {
            Setting::set('app_latest_version', $remoteVer);
            Setting::set('app_update_changelog', $changelog !== '' ? $changelog : 'نسخه جدید اپلیکیشن آماده شد.');
            Setting::set('app_update_title', trim((string)($manifest['title'] ?? '')) !== '' ? trim((string)$manifest['title']) : 'Connectix');
            Setting::set('app_update_source', 'auto');
            Setting::set('app_update_published_at', date('Y-m-d H:i:s'));
            Setting::set('app_update_auto_code', (string)($manifest['code'] ?? ''));

            $status['published_version'] = $remoteVer;
            $status['published_at'] = date('Y-m-d H:i:s');
            $status['action'] = 'published';

            // Notify admins on the Telegram panel bot (best effort)
            try {
                require_once __DIR__ . '/TelegramBot.php';
                $msg = "🚀 <b>انتشار خودکار نسخه جدید اپلیکیشن اندروید</b>\n\n"
                    . "🏷 نسخه: <code>{$remoteVer}</code>\n"
                    . "📅 زمان: " . date('Y-m-d H:i:s') . "\n"
                    . "📝 " . (mb_strlen($changelog) > 220 ? mb_substr($changelog, 0, 220) . '…' : $changelog);
                TelegramBot::sendMessage($msg);
            } catch (Throwable $e) {}
        } else {
            $status['action'] = ($source === 'admin') ? 'manual_override_active'
                : (!$enabled ? 'updates_disabled'
                : 'up_to_date');
        }

        // Mirror APK assets onto the panel host: the in-app updater downloads
        // "$baseUrl/Connectix-*.apk" from THIS server (fast + works inside Iran,
        // where the GitHub fallback fails with a connection error).
        try {
            require_once __DIR__ . '/AppApkMirror.php';
            $mirrorRes = AppApkMirror::mirror($release, false, $remoteVer, (string)($manifest['code'] ?? ''));
            $status['apk_mirror'] = $mirrorRes['files'];
            if ($mirrorRes['changed']) {
                $status['apk_mirror_changed'] = date('Y-m-d H:i:s');
            }
            if (!$mirrorRes['ok']) {
                $status['apk_mirror_error'] = $mirrorRes['error'] ?? 'failed';
            }
        } catch (Throwable $e) {
            $status['apk_mirror_error'] = $e->getMessage();
        }

        Setting::set('app_release_status_cache', json_encode($status));
        return $status;
    }

    /** Read the cached status for the admin UI (no network access) */
    public static function status(): array
    {
        $s = json_decode(Setting::get('app_release_status_cache', '{}'), true) ?: [];
        $s['current_version'] = Updater::CURRENT_VERSION;
        $s['published_version'] = trim((string)Setting::get('app_latest_version', ''));
        $s['source'] = (string)Setting::get('app_update_source', 'auto');
        $s['enabled'] = Setting::get('app_update_enabled', '1') !== '0';
        $s['checked_at'] = (string)Setting::get('app_release_last_check', '') !== ''
            ? date('Y-m-d H:i:s', (int)Setting::get('app_release_last_check', '0'))
            : 'هنوز بررسی نشده';
        return $s;
    }

    private static function fetchJson(string $url): ?array
    {
        // Unique bust per call: GitHub release-asset URLs do NOT change when CI
        // re-uploads the same asset name, so transparent egress caches may
        // serve the previous manifest (same trap that bit the APK mirror).
        $sep = (strpos($url, '?') === false) ? '?' : '&';
        $url = $url . $sep . 'cb=' . (string)time() . rand(1000, 9999);

        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_TIMEOUT => 15,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_USERAGENT => 'Connectix-App-Release-Sync/1.0',
            CURLOPT_HTTPHEADER => ['Cache-Control: no-cache, no-store', 'Pragma: no-cache'],
        ]);
        $body = curl_exec($ch);
        $http = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if ($http !== 200 || !is_string($body)) return null;
        $data = json_decode($body, true);
        return is_array($data) ? $data : null;
    }
}
