name: connectix_vpn
description: Connectix Professional Multiplatform VPN Client - ULTRA Dual-Core Xray + sing-box + v4.0.50 FIX VERSION DISPLAY + AUTO API KEY FROM WEB PANEL
publish_to: 'none'
version: 4.0.50+84

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_vless: ^1.1.6
  url_launcher: ^6.1.14
  percent_indicator: ^4.2.3
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.0
  wakelock_plus: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
